import {defaults,validate,array,plant} from './geometry.mjs';
const $=id=>document.getElementById(id),canvas=$('drawing'),ctx=canvas.getContext('2d');let settings={...defaults},model=array(settings),yaw=-.6,pitch=.65,scale=30,pan=[0,0],projected=[],drag=null,selected=null;
const money=n=>n.toLocaleString('en-GB');
function point3(p){let [x,y,z]=p;const a=x*Math.cos(yaw)-y*Math.sin(yaw),b=x*Math.sin(yaw)+y*Math.cos(yaw);return [innerWidth/2+pan[0]+a*scale,innerHeight/2+pan[1]+(b*Math.sin(pitch)-z*Math.cos(pitch))*scale];}
function poly(points){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.stroke();}
function draw(){const d=devicePixelRatio||1;canvas.width=Math.round(innerWidth*d);canvas.height=Math.round(innerHeight*d);ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,innerWidth,innerHeight);projected=[];ctx.strokeStyle='#333';ctx.lineWidth=.8;
 for(const m of model.modules){const pts=m.corners.map(point3);ctx.lineWidth=selected===m.id?2:.7;poly(pts);projected.push({id:m.id,pts});ctx.lineWidth=.8;for(const b of m.boxes){const p=point3(b);ctx.strokeRect(p[0]-2,p[1]-2,4,4);}}
 ctx.strokeStyle='#aaa';ctx.lineWidth=.5;for(const m of model.modules.filter(m=>m.row===1)){for(const i of [0,1]){const p=m.corners[i];ctx.beginPath();ctx.moveTo(...point3(p));ctx.lineTo(...point3([p[0],p[1],0]));ctx.stroke();}}
 ctx.fillStyle='#555';ctx.font='12px Arial';ctx.fillText('N',...point3([0,model.run+2,0]));
}
function fit(){pan=[0,0];scale=Math.max(2,Math.min((innerWidth-(innerWidth>650?300:40))/(model.span+model.run*2+4),(innerHeight-180)/(model.run*2+4)));draw();}
function apply(next){settings=validate(next);model=array(settings);selected=null;const p=plant(settings);$('counts').textContent=`${money(p.modules)} modules\n${money(p.strings)} strings\n${money(p.inverters)} inverters\n${money(p.blocks)} blocks\n${p.actualDCMW.toFixed(3)} MW DC\nFinal inverter: ${p.lastInverterStrings} strings`;$('summary').textContent=`${model.modules.length} modules shown · width ${model.span.toFixed(2)} m · slope ${model.run.toFixed(2)} m · top ${(model.height+model.rise).toFixed(2)} m`;$('error').textContent='';draw();}
function fields(){for(const el of $('form').elements)if(el.name&&el.name in settings)el.value=settings[el.name];$('direction').value=String(settings.azimuth);}
$('form').addEventListener('input',()=>{try{const next={...settings};for(const el of $('form').elements)if(el.name)next[el.name]=el.type==='number'?Number(el.value):el.value;next.azimuth=Number($('direction').value);apply(next);}catch(e){$('error').textContent=e.message;}});
$('menu').onclick=()=>{$('settings').hidden=!$('settings').hidden;$('menu').setAttribute('aria-expanded',String(!$('settings').hidden));};$('fit').onclick=fit;$('plan').onclick=()=>{pitch=Math.PI/2;yaw=0;fit();};$('three').onclick=()=>{pitch=.65;yaw=-.6;fit();};$('full').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.().catch(()=>{});else document.exitFullscreen?.();};
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('save').onclick=()=>download('array-settings.json',JSON.stringify(settings,null,2),'application/json');
$('load').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>20000)throw Error('Settings file is too large');apply(JSON.parse(await f.text()));fields();fit();}catch(err){$('error').textContent=err.message;}e.target.value='';};
$('svg').onclick=()=>{const paths=projected.map(m=>`<polygon points="${m.pts.map(p=>p.map(x=>x.toFixed(3)).join(',')).join(' ')}"/>`).join('');download('array-drawing.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${innerWidth} ${innerHeight}"><title>Array wireframe; projected view; geometry units metres</title><g fill="none" stroke="#222" stroke-width="0.7">${paths}</g></svg>`,'image/svg+xml');};
canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,pan:e.button===2};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(drag.pan){pan[0]+=dx;pan[1]+=dy;}else{yaw+=dx*.006;pitch=Math.max(.05,Math.min(Math.PI/2,pitch+dy*.006));}drag.x=e.clientX;drag.y=e.clientY;draw();};
canvas.onpointerup=e=>{if(drag&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)<4){let best=Infinity,hit=null;for(const m of projected){const c=m.pts.reduce((a,p)=>[a[0]+p[0]/4,a[1]+p[1]/4],[0,0]);const distance=Math.hypot(c[0]-e.clientX,c[1]-e.clientY);if(distance<best&&distance<40){best=distance;hit=m.id;}}selected=hit;const m=model.modules.find(m=>m.id===hit);$('selection').textContent=m?`Module ${m.id} · face ${m.wing+1} · row ${m.row} · column ${m.column} · ${m.boxes.length} assumed boxes`:'Synthetic geometry · metres · editable assumptions';}drag=null;draw();};canvas.onpointercancel=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();scale=Math.max(.1,Math.min(500,scale*Math.exp(-e.deltaY*.001)));draw();};window.addEventListener('resize',draw);apply(settings);fields();fit();
// Read-only diagnostic state for automated geometry/browser checks.
window.arrayStudio={get state(){return {settings:{...settings},moduleCount:model.modules.length,plant:plant(settings)};}};
