import {siteModel,tableAt,validatePlacements,overlapsFor} from './site.mjs';
import {defaults,validate,array,plant} from './geometry.mjs';
const $=id=>document.getElementById(id),canvas=$('drawing'),ctx=canvas.getContext('2d');let settings={...defaults},model=array(settings),yaw=-.6,pitch=.65,scale=30,pan=[0,0],projected=[],drag=null,selected=null,view='array',site=siteModel(settings),placements={},selectedTable=0,siteHits=[],moving=false,siteZoom=1,siteFrame=null;
const money=n=>n.toLocaleString('en-GB');
function point3(p){let [x,y,z]=p;const a=x*Math.cos(yaw)-y*Math.sin(yaw),b=x*Math.sin(yaw)+y*Math.cos(yaw);return [innerWidth/2+pan[0]+a*scale,innerHeight/2+pan[1]+(b*Math.sin(pitch)-z*Math.cos(pitch))*scale];}
function poly(points){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.stroke();}
function draw(){const count=tableAt(site,selectedTable,placements).modules;$('summary').textContent=view==='site'?`${money(site.modules)} modules in ${money(site.tables)} arrays`:`${count} modules shown - width ${model.span.toFixed(2)} m - slope ${model.run.toFixed(2)} m - top ${(model.height+model.rise).toFixed(2)} m`;$('arrayIndex').value=selectedTable+1;const d=devicePixelRatio||1;canvas.width=Math.round(innerWidth*d);canvas.height=Math.round(innerHeight*d);ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,innerWidth,innerHeight);projected=[];ctx.strokeStyle='#a7bacb';ctx.lineWidth=.8;if(view==='site'){drawSite();return;}
 for(const m of model.modules.slice(0,tableAt(site,selectedTable,placements).modules)){const pts=m.corners.map(point3);ctx.lineWidth=selected===m.id?2:.7;poly(pts);projected.push({id:m.id,pts});ctx.lineWidth=.8;for(const b of m.boxes){const p=point3(b);ctx.strokeRect(p[0]-2,p[1]-2,4,4);}}
 ctx.strokeStyle='#647b91';ctx.lineWidth=.55;for(const member of model.structure){ctx.beginPath();member.points.map(point3).forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();}
 ctx.fillStyle='#a7bacb';ctx.font='12px Arial';ctx.fillText('N',...point3([0,model.run+2,0]));
}
function fit(){if(view==='site'){pan=[0,0];siteZoom=1;siteFrame=[0,0,site.width,site.height];for(const p of Object.values(placements)){siteFrame[0]=Math.min(siteFrame[0],p.x);siteFrame[1]=Math.min(siteFrame[1],p.y);siteFrame[2]=Math.max(siteFrame[2],p.x+site.size[0]);siteFrame[3]=Math.max(siteFrame[3],p.y+site.size[1]);}draw();return;}pan=[0,0];scale=1;const pts=[...model.modules.flatMap(m=>m.corners),...model.structure.flatMap(m=>m.points)].map(point3).map(p=>[p[0]-innerWidth/2,p[1]-innerHeight/2]),min=[0,1].map(i=>Math.min(...pts.map(p=>p[i]))),max=[0,1].map(i=>Math.max(...pts.map(p=>p[i])));scale=Math.min((innerWidth-80)/Math.max(1,max[0]-min[0]),(innerHeight-180)/Math.max(1,max[1]-min[1]));pan=[-(min[0]+max[0])/2*scale,-(min[1]+max[1])/2*scale+20];draw();}
function apply(next){settings=validate(next);model=array(settings);site=siteModel(settings);siteFrame=null;placements=Object.fromEntries(Object.entries(placements).filter(([i])=>Number(i)<site.tables));selectedTable=Math.min(selectedTable,site.tables-1);selected=null;const p=plant(settings);$('counts').textContent=`${money(p.modules)} modules\n${money(p.strings)} strings\n${money(p.inverters)} inverters\n${money(p.blocks)} blocks\n${p.actualDCMW.toFixed(3)} MW DC\nFinal inverter: ${p.lastInverterStrings} strings`;$('summary').textContent=`${model.modules.length} modules shown · width ${model.span.toFixed(2)} m · slope ${model.run.toFixed(2)} m · top ${(model.height+model.rise).toFixed(2)} m`;$('error').textContent='';draw();}
function fields(){for(const el of $('form').elements)if(el.name&&el.name in settings)el.value=settings[el.name];$('direction').value=String(settings.azimuth);heightFields();}
function heightFields(){const form=$('form');form.elements.tilt.disabled=settings.heightMode==='edges';form.elements.upperHeight.disabled=settings.heightMode==='tilt';form.elements.tilt.value=Number(settings.tilt.toFixed(4));form.elements.upperHeight.value=Number(settings.upperHeight.toFixed(4));}
$('raised-preset').onclick=()=>{apply({...settings,heightMode:'edges',height:4,upperHeight:5});fields();fit();};
document.querySelectorAll('[data-preset]').forEach(button=>button.onclick=()=>{const key=button.dataset.preset;apply({...settings,rows:key==='ew'?5:1,orientation:'portrait',layout:key==='ew'?'east-west':'fixed',azimuth:{ew:90,south:180,east:90,west:270}[key]});fields();fit();});
$('form').addEventListener('input',()=>{try{const next={...settings};for(const el of $('form').elements)if(el.name)next[el.name]=el.type==='number'?Number(el.value):el.value;next.azimuth=Number($('direction').value);apply(next);heightFields();fit();}catch(e){$('error').textContent=e.message;}});
$('menu').onclick=()=>{$('settings').hidden=!$('settings').hidden;$('menu').setAttribute('aria-expanded',String(!$('settings').hidden));};$('fit').onclick=fit;$('plan').onclick=()=>{view='array';pitch=Math.PI/2;yaw=0;fit();};$('three').onclick=()=>{view='array';pitch=.65;yaw=-.6;fit();};$('full').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.().catch(()=>{});else document.exitFullscreen?.();};
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('save').onclick=()=>download('array-settings.json',JSON.stringify({schema:'array-layout/1',settings,placements:Object.entries(placements).map(([index,p])=>({index:Number(index),...p}))},null,2),'application/json');
$('load').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw Error('Settings file is too large');const data=JSON.parse(await f.text());if(data.schema==='array-layout/1'){const next=validate(data.settings),moves=validatePlacements(data.placements,siteModel(next));apply(next);placements=moves;}else{apply(data);placements={};}fields();fit();}catch(err){$('error').textContent=err.message;}e.target.value='';};
$('svg').onclick=()=>{const outlines=view==='site'?siteHits.map(h=>({pts:[h.p,[h.p[0]+h.w,h.p[1]],[h.p[0]+h.w,h.p[1]+h.h],[h.p[0],h.p[1]+h.h]]})):projected;const paths=outlines.map(m=>`<polygon points="${m.pts.map(p=>p.map(x=>x.toFixed(3)).join(',')).join(' ')}"/>`).join('');const members=view==='array'?model.structure.map(m=>{const [a,b]=m.points.map(point3);return `<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}"/>`;}).join(''):'';download('array-drawing.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${innerWidth} ${innerHeight}"><title>${view==='site'?'Sampled plant overview':'Selected array wireframe'}; projected screen coordinates; source geometry in metres</title><g fill="none" stroke="#222" stroke-width="0.7">${paths}${members}</g></svg>`,'image/svg+xml');};
canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{if(view==='site'){if(e.button===2){drag={sitePan:true,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);return;}const hit=[...siteHits].reverse().find(h=>e.clientX>=h.p[0]&&e.clientX<=h.p[0]+h.w&&e.clientY>=h.p[1]&&e.clientY<=h.p[1]+h.h);if(hit){selectedTable=hit.index;$('arrayIndex').value=selectedTable+1;canvas.setPointerCapture(e.pointerId);if(moving){const t=tableAt(site,hit.index,placements);drag={site:true,x:e.clientX,y:e.clientY,origin:t,factor:siteScale()};}else{$('selection').textContent='Array '+(hit.index+1)+' - '+tableAt(site,hit.index,placements).modules+' modules - move or open 3D';}draw();}return;}drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,pan:e.button===2};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;if(drag.sitePan){pan[0]+=e.clientX-drag.x;pan[1]+=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;draw();return;}if(drag.site){const factor=drag.factor;setPlacement({x:drag.origin.x+(e.clientX-drag.x)/factor,y:drag.origin.y-(e.clientY-drag.y)/factor});draw();return;}const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(drag.pan){pan[0]+=dx;pan[1]+=dy;}else{yaw+=dx*.006;pitch=Math.max(.05,Math.min(Math.PI/2,pitch+dy*.006));}drag.x=e.clientX;drag.y=e.clientY;draw();};
canvas.onpointerup=e=>{if(view==='site'){drag=null;draw();return;}if(drag&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)<4){let best=Infinity,hit=null;for(const m of projected){const c=m.pts.reduce((a,p)=>[a[0]+p[0]/4,a[1]+p[1]/4],[0,0]);const distance=Math.hypot(c[0]-e.clientX,c[1]-e.clientY);if(distance<best&&distance<40){best=distance;hit=m.id;}}selected=hit;const m=model.modules.find(m=>m.id===hit);$('selection').textContent=m?`Module ${m.id} · face ${m.wing+1} · row ${m.row} · column ${m.column} · ${m.boxes.length} assumed boxes`:'Synthetic geometry · metres · editable assumptions';}drag=null;draw();};canvas.onpointercancel=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();if(view==='site'){siteZoom=Math.max(.2,Math.min(20,siteZoom*Math.exp(-e.deltaY*.001)));draw();return;}scale=Math.max(.1,Math.min(500,scale*Math.exp(-e.deltaY*.001)));draw();};window.addEventListener('resize',fit);apply(settings);fields();fit();
// Read-only diagnostic state for automated geometry/browser checks.
window.arrayStudio={get state(){return {settings:{...settings},moduleCount:tableAt(site,selectedTable,placements).modules,plant:plant(settings),view,tableCount:site.tables,selectedTable,movedArrays:Object.keys(placements).length,selectedPosition:{...tableAt(site,selectedTable,placements)},selectedScreen:siteHits.find(h=>h.index===selectedTable),projectedBounds:projected.length?[Math.min(...projected.flatMap(m=>m.pts.map(p=>p[0]))),Math.min(...projected.flatMap(m=>m.pts.map(p=>p[1]))),Math.max(...projected.flatMap(m=>m.pts.map(p=>p[0]))),Math.max(...projected.flatMap(m=>m.pts.map(p=>p[1])))]:null};}};

function siteScale(){const b=siteFrame??[0,0,site.width,site.height];return siteZoom*Math.max(1e-9,Math.min((innerWidth-80)/(b[2]-b[0]),(innerHeight-150)/(b[3]-b[1])));}
function drawSite(){const overlaps=overlapsFor(site,selectedTable,placements);$('selection').textContent='Array '+(selectedTable+1)+' - '+overlaps.length+' overlapping array bounds';const b=siteFrame??[0,0,site.width,site.height],k=siteScale(),left=(innerWidth-(b[2]-b[0])*k)/2+pan[0],top=(innerHeight-(b[3]-b[1])*k)/2+pan[1];siteHits=[];const stride=site.groupSize;const shown=new Set([selectedTable,...Object.keys(placements).map(Number)]);for(let i=0;i<site.tables;i+=stride)shown.add(i);for(const i of shown){const t=tableAt(site,i,placements),p=[left+(t.x-b[0])*k,top+(b[3]-t.y-site.size[1])*k],w=Math.max(2,site.size[0]*k),h=Math.max(2,site.size[1]*k);ctx.lineWidth=i===selectedTable?1.7:.5;ctx.strokeRect(...p,w,h);siteHits.push({index:i,p,w,h});}ctx.fillStyle='#a7bacb';ctx.font='12px Arial';ctx.fillText(site.tables.toLocaleString()+' arrays ? '+site.modules.toLocaleString()+' modules ? overview samples 1 in '+stride,16,innerHeight-62);ctx.fillText('Synthetic rectangular layout - 3 m spacing assumption - click a shown array to select',16,innerHeight-44);}
$('site').onclick=()=>{view='site';fit();};$('move').onclick=()=>{view='site';moving=!moving;$('move').textContent=moving?'Finish move':'Move array';draw();};

$('arrayIndex').onchange=()=>{const n=Number($('arrayIndex').value);if(!Number.isInteger(n)||n<1||n>site.tables){$('error').textContent='Array number must be 1 to '+site.tables;return;}selectedTable=n-1;$('error').textContent='';$('selection').textContent='Array '+n+' - '+tableAt(site,selectedTable,placements).modules+' modules';draw();};

document.querySelectorAll('[data-step]').forEach(button=>button.onclick=()=>{const t=tableAt(site,selectedTable,placements),delta={west:[-1,0],east:[1,0],north:[0,1],south:[0,-1]}[button.dataset.step];setPlacement({x:t.x+delta[0],y:t.y+delta[1]});view='site';draw();});

function setPlacement(p){try{if(!(selectedTable in placements)&&Object.keys(placements).length>=10000)throw Error('Maximum 10000 moved arrays');validatePlacements([{index:selectedTable,...p}],site);placements[selectedTable]=p;$('error').textContent='';}catch(e){$('error').textContent=e.message;}}
